lua/fzf-lua/providers/manpages.lua

If there are multiple man pages of the same name in different sections, `getmanpage(selected)` removes the section number, and the wrong man page is opened. In man pages, references to other man pages have no space between name and section number either.

open the correct man page section

---

lua/fzf-lua/actions.lua

Hi, 
First, thanks for making this plugin! It is such a nice lua version of fzf.vim :) 
I'm interested in opening selections in "the background", i.e. just adding them to the buffer list but not switching to them. What are your thoughts about adding it to such an action? I didn't add them any default keybindings since if someone wants to use this they can create keybinding in their user config.

Add open in background file buffer

---

lua/fzf-lua/core.lua
lua/fzf-lua/utils.lua

1) Faster method to determine if in git repo
2) Bypass entirely if git icons disabled
These two changes make fzf-lua perform _much_ faster when run in large codebases. `git status` takes between half a second a second to run on our large codebase, but this change makes fzf-lua nearly as snappy as fzf.vim.

Optimize git performance

---

README.md
lua/fzf-lua/config.lua
lua/fzf-lua/providers/lsp.lua

`rust-analyzer` LSP server loads a new LSP server instance and pushes diagnostics for dependencies (external crates) when you open their files (via "jump to definition", etc.).

add lsp.workspace_diag_only_cwd option to filter out diagnostics entries from files outside of the current working directory

---

lua/fzf-lua/previewer/builtin.lua

This way, if the user has defined cursorlineopt=number elsewhere, we
override it to behave as intended.

Set cursorlineopt=both in the builtin previewer

---

lua/fzf-lua/actions.lua
lua/fzf-lua/config.lua

Addresses #51. Implements opening previous commits in a read only buffer/split/tab and corresponding actions for b_commits. Also implements checkout action for git commits.

Add actions to checkout and inspect previous git commits

---

lua/fzf-lua/previewer/builtin.lua

Whenever the file ends with newline, the builtin previewer was adding an
empty line at the end of the file. That's a side effect splitting and
rejoining the lines with \n. Basically, when we split a\nb\nc\n we get
{'a', 'b', 'c', ''}, then nvim_buf_set_lines treats each item in the
table as a line, and inserts an empty line at the end.
We do need to account for files that don't end with a new line though,
hence the check.
I don't have a way to test the \r\n logic locally, no Windows hosts
around, but it should work too.
Before:
(line 23 doesn't really exist, file only has 22 lines: https://github.com/fsouza/dotfiles/blob/main/.github/dependabot.yml)
After:

Fix empty line in the builtin previewer

---

lua/fzf-lua/config.lua

Addresses #86 by adding --reflog flag to the "git log" command which populates the list of commits. See [reflog docs](https://git-scm.com/docs/git-reflog) for more info.

Fix loss of git records after checking out older commits

---

lua/fzf-lua/actions.lua
lua/fzf-lua/path.lua
lua/fzf-lua/providers/git.lua

This matches the behavior of both fzf.vim and telescope.nvim.
It also fixes a bug with the "git_buf_edit" action if the cwd is not in
the git root.

Improve git commands so they always run in the git root directory

---

lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/win.lua

See :help local-options for more details, but essentially, we have to be
very careful with how we set window-local options on popup windows,
because buffers might take some window-local options from the last
window they were displayed in with them to the new window in certain
circumstances.
This commit changes the backup/restore for the window options so that
the possible window-local options that might get clobbered are saved
from the original active window and reapplied to the preview window just
before it's closed. This ensures any buffers loaded from the picker will
have the same window options applied that were in the active window when
fzf was opened.

Builtin previewer: improve mechanism for backing up/restoring winopts

---

README.md

Git command update in README: `git_branch` -> `git_branches`. The command in `builtin` shows the correct name already which is `git_branches`.

Very minor README change

---

README.md
lua/fzf-lua/config.lua
lua/fzf-lua/core.lua

Fixes #98 
This option helps kitty terminal users to render double-width icons.

Add file_icon_padding option

---

lua/fzf-lua/config.lua
lua/fzf-lua/core.lua
lua/fzf-lua/path.lua
lua/fzf-lua/providers/buffers.lua
lua/fzf-lua/utils.lua

This improves the colors for file icons if nvim-web-devicons is available. If it is, fzf-lua now uses colors defined by the plugin for the file icons.
This should also improve the performance of `make_entry_file()` by simplifying the regex(es) applied to each line from the callback. It avoids pattern matching with the end of string character (`$`) which in my testing is slower than looping through matches with `gmatch`. It also fixes a bug where ansi escape codes could affect cwd/relative path logic.
This is an alternate attempt to fix the same issue as #100 but also improves the colors.

File icons: use colors from nvim-web-devicons if available

---

README.md
lua/fzf-lua/config.lua
lua/fzf-lua/core.lua

`fzf.vim` provides the global option `fzf_colors`, which allows the user to match some of the fzf highlight groups with vim highlight groups. Without `--color`, the fzf colorscheme doesn't always acceptably match the vim one (for example when using light themes). Setting the enviroment option `$FZF_DEFAULT_OPS` can help, but only if you are not changing vim colorschemes often. This PR should help in this regard. We should also probably discuss which vim highlight groups should match to which fzf `--color` options.
Great plugin, btw! I've decided to switch to it completely today, after using `fzf.vim` for a while now and it's been nothing but smooth sailing.

Add support for fzf --color option

---

lua/fzf-lua/core.lua
lua/fzf-lua/path.lua
lua/fzf-lua/providers/git.lua

Couple improvements here:
- `path.tail()` and `path.extension()` can just look backward from the end for the first separator and take a substring. No pattern matching is done and they only have to look at the number of characters that is the size of the result instead of the size of the input sub the size of the result. This is even faster than the current method.
- improve get_devicon() to be case-insensitive

More performance improvements 

---

lua/fzf-lua/providers/lsp.lua

Implentation for https://github.com/ibhagwan/fzf-lua/issues/124
Usage example:
```lua
local fzf_lua = require('fzf-lua')
local actions = require('fzf-lua.actions')
fzf_lua.lsp_definitions({
jump_to_single_result = true,
jump_to_single_result_action = actions.file_vsplit
})
```

improvement: lsp provider uses actions

---

lua/fzf-lua/path.lua

found this bug independently of #204 / https://github.com/ibhagwan/fzf-lua/commit/454b0ba48c89f05ca16023cb34b1ae21c30ff8af and wrote this fix.
unfortunately it still occured with https://github.com/ibhagwan/fzf-lua/commit/454b0ba48c89f05ca16023cb34b1ae21c30ff8af  (like grepping and finding a result `[src](https://domain.tld)`).
although it may not be as elegant i figured i'd create a pr with my initial fix.
thanks for the well documented code btw :)

fix: too broad uri regex match - restrict to jdt / file

---

lua/fzf-lua/actions.lua

When calling vim.fn.feedkeys for commands or searches ,which means it is prefixed by ":" or "/", one of those keys could be remapped to something else. Calling feedkeys with "n" means this mapping would be ignored.

Do not remap when calling feedkeys (closes #258)

---

lua/fzf-lua/make_entry.lua

This fix removes the nbsp. Kitty needs a normal space to extend the icon size.

fix devicon size in kitty using file_icon_padding

---

README.md

Previously defaulted to master branch, this tells it to use main instead

Correct vim-plug install instructions

---

lua/fzf-lua/previewer/builtin.lua

To correctly match some common highlight groups such as `Float`, `Normal` etc, word boundaries
should be set, otherwise wrong highlight group is shown in the preview window. 
Also removes search highlighting of the trailing space.

Fix highlights previewer

---

lua/fzf-lua/previewer/builtin.lua

Fixes two issues:
* Preview wasn't showing the jump location when the file was outside of
the pwd.
* Preview wasn't showing the jump location when the jump was on a blank
line in the current buffer.

fix(jumps): fix preview not showing correctly

---

lua/fzf-lua/providers/quickfix.lua

`opts` was being used before it was normalized causing the quickfix
command to fail when used without any options.

fix(quickfix): prevent indexing opts when nil

---

lua/fzf-lua/actions.lua

**Expected behavior**: `action.buf_switch` in combination with `fzf_lua.tabs()` switches to the selected buffer in the selected tab.
**Actual behavior** in `main`: The action switches to the selected tab but the code crashes before selecting the buffer.
Here's the problem:
With `fzf_lua.tabs()`, `tabnr` is a string:
https://github.com/ibhagwan/fzf-lua/blob/786d06bc51de2dba9ccf5b80571ad03c65080f80/lua/fzf-lua/actions.lua#L280
but `tabnr` gets passed to `vim.api.nvim_tabpage_list_wins`, which expects a number:
https://github.com/ibhagwan/fzf-lua/blob/786d06bc51de2dba9ccf5b80571ad03c65080f80/lua/fzf-lua/actions.lua#L288
https://github.com/ibhagwan/fzf-lua/blob/817df87a8ebd2137aa42c2fa370e33b980e313dc/lua/fzf-lua/utils.lua#L469-L470
**Fix**: Convert `tabnr` to a number.

fix(buf_switch): winid_from_tab_buf expects number

---

lua/fzf-lua/providers/lsp.lua

Hi. I found code_actions of elm-language-server doesn't work with `:FzfLua lsp_code_actions`, while `:lua vim.lsp.buf.code_action()` works.
I investigated the code to find `data` argument was not passed on `get_line_diagnostics` function, and the problem goes away by passing it.
According to [lsp specification about Diagnostic](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic), seems like it should be passed.
Thanks.

put diagnostic.data on get_line_diagnostics

---

lua/fzf-lua/init.lua

Got a report here about fzf-lua: https://github.com/stevearc/dressing.nvim/issues/64
The lazy loading was forwarding the function arguments, but not the return value. For `find_files` this is fine, but for `fzf_wrap` we expect it to return a function.

fix: lazy loading of fzf_wrap

---

lua/fzf-lua/core.lua

Hey there, love your lua glue to fzf !
Would it be possible to pass down the `opts` to `fn_selected` in fzf_wrap so we can better customize it ?
My use case is to operate multi select on rg grep sending it to the quickfix list like so:
```lua
local function grep_sel_to_qf(selected, opts)
local qf_list = {}
for i = 1, #selected do
local file = fzf_lua.path.entry_to_file(selected[i], opts)
local text = selected[i]:match(":%d+:%d?%d?%d?%d?:?(.*)$")
table.insert(qf_list, {
filename = file.bufname or file.path,
lnum = file.line,
col = file.col,
text = text,
})
end
vim.fn.setqflist(qf_list, "r")
end
local function fn_selected_multi(selected, opts)
if not selected then
return
end
-- first element of "selected" is the keybind pressed
if #selected <= 2 then
fzf_lua.actions.act(opts.actions, …
```

fix(fn_selected): pass down opts to fn_selected in fzf_wrap

---

lua/fzf-lua/cmd.lua

Although not directly exposed, the logical condition in run_command is wrong and makes the second part of the `and` pointless. Instead `or` would do the correct evaluation.

fix(run_command): wrong logical condition

---

lua/fzf-lua/cmd.lua

Won't happen often, but if a user mistypes a command they will be presented with some feedback like `[Fzf-lua] invalid command 'wrong_cmd_test'`

feat(run_command): provide user feedback in case of wrong command

---

README.md
doc/fzf-lua.txt
scripts/mini.sh

The nvim-web-devicons repo was transferred from kyazdani42/nvim-web-devicons to [nvim-tree/nvim-web-devicons](https://github.com/nvim-tree/nvim-web-devicons).
This updates the docs to point to the updated repo.

docs: Update nvim-web-devicons references

---

.github/workflows/luarocks-release.yaml

We have released a new version of luarocks-tag-release that automatically detects neovim plugin directories
(based on `:help runtimepath`) and adds them to the rockspec if found.
The `v3` tag is a mutable tag that lets you benefit from improvements and new features without breaking changes.

cd: bump luarocks-tag-release to v3

---

lua/fzf-lua/path.lua

After I got a new laptop from my company I noticed that the HOME folder in `tab_cwd` was not shortened to a tilde. What changed? After digging a little a realized that my Unix username changed from a purely alphanumeric one to `name-family_name` with a dash ('-'), and that is a magic character in lua patterns.
Using the solution from https://stackoverflow.com/a/34953646, every non-alphanumeric character is escaped before composing the HOME folder pattern.

Escaping HOME folder pattern

---

lua/fzf-lua/providers/diagnostic.lua

Since diag_results is used in in vim.schedule()d callback, the buffers may have become invalid when the callback is executed. So the buffers' validity should be checked.

fix(diagnostic): buffer might have become invalid

---

lua/fzf-lua/utils.lua

If using the `HEAD` version of fzf, this error is thrown when trying to use the `buffers` function
```
E5108: Error executing lua: ...ng/.local/share/neovim/lazy/fzf-lua/lua/fzf-lua/core.lua:755: attempt to compare nil with number
stack traceback:
...ng/.local/share/neovim/lazy/fzf-lua/lua/fzf-lua/core.lua:755: in function 'convert_reload_actions'
...re/neovim/lazy/fzf-lua/lua/fzf-lua/providers/buffers.lua:234: in function 'buffers'
```
```sh
$ fzf --version
HEAD-e619b7c (brew)
```
```
NVIM v0.10.0-dev-1617+g143a17833-Homebrew
Build type: Release
LuaJIT 2.1.0-beta3
```

fix: check if version is HEAD

---

lua/fzf-lua/providers/lsp.lua

This PR provides a optional filter to give user the ability to filter the results of the LSP calls before viewing.
This is helpful in situations the user doesn't want to list some references. Here is an example usage in Go to filter out all the items in mock files:
```lua
local check = "_mock.go"
local filter = function(items)
local ret = {}
for _, item in ipairs(items) do
if item.filename:sub(-#check) ~= check then
table.insert(ret, item)
end
return ret
end
end
require("fzf-lua").lsp_implementations({
jump_to_single_result = true,
filter = filter,
})
```

feat(lsp): add optional filter function

---

lua/fzf-lua/providers/diagnostic.lua

Fixes #854 
The regression was caused by [this change in the diagnostics API](https://github.com/neovim/neovim/pull/24736). The changes from this PR should still with versions prior to that change though.

fix(diagnostics): always provide min/max

---

.luarc.json

When working on a previous PR, I had to set this in order to get the right completions.

chore(lua): use $VIMRUNTIME

---

README.md

`vim-plug` enforces single quotes, double quotes issue an error

vim-plug single quotes

---

plugin/fzf-lua.vim

Completion items for arguments to the `:FzfLua` command are now sorted in the alphabetical order. Previously it was given in a random order.

fix(completion): sort completion items for the :FzfLua command

---

lua/fzf-lua/actions.lua
lua/fzf-lua/providers/nvim.lua

> fix(keymaps): Fix keymaps error when desc is a multi-line string
The textual description of a keymap can have more than one lines,
in which case the previewer was emitting errors. An easy fix here would
be to join all the lines (so that 1 keymap entry == 1 line in fzf).
BEFORE:
AFTER:
> fix(keymaps): Fix whitespace handling in keymap_apply action
Need to exclude trailing whitespaces to get the lhs keycode.
For example, an entry
"n │ c                                        │ (desc)"
should be resolved to `c`, not `c                                    `.

Fix two bugs (whitespace and multi-line desc) in keymaps

---

lua/fzf-lua/defaults.lua

A bit pedantic, but I think it makes sense to use the same casing as the other defaults :)

fix(highlights): uppercase prompt

---

lua/fzf-lua/actions.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/providers/files.lua
lua/fzf-lua/providers/git.lua
lua/fzf-lua/providers/tags.lua
lua/fzf-lua/utils.lua

`nvim_buf_get_name` always returns a string, so checking that the result isn't falsy it's not needed :)

chore: remove redundant bufname checks

---

lua/fzf-lua/actions.lua

Now "marks" will take you to the line and column of the mark, not just the start of the line.

fix: marks should go to line and column

---

lua/fzf-lua/providers/nvim.lua

The previewer shows the wrong column for marks (off by one).
(This was the case even before #892)

fix: the previewer shows the wrong column for marks

---

lua/fzf-lua/providers/git.lua

This is equivalent as `git stash list -G<regex>` in the command line.
Example:
:lua require("fzf-lua").git_stash { search = 'pattern' }
:FzfLua git_stash search=(some|regex|pattern)
This will be useful to quickly find the stash for some keyword **by content**. DEMO:
... when you have really many clutters on the stash list :P

feat(git_stash): Allow `search` to search stash list for regex keyword

---

lua/fzf-lua/init.lua

Using `vim.fn.serverstart()` can cause conflicts when different nvim instances have the same PID. This can happen if nvim runs sandboxed in its own PID namespace, for example when using Flatpak. The two different instances can have the same PID in their own namespace.
As noted in the docs, neovim will use the default path of `stdpath("run").."/{name}.{pid}.{counter}"`, however if the PID is the same, the RPC servers will clash.
To accomodate this use-case, the RPC server will be started with a reasonably unique name by using a timestamp in its name. This avoids name clashes.

Generate unique name for RPC server

---

lua/fzf-lua/previewer/builtin.lua

Noticed that there was a small typo in the docs/comments

Fixed typo in docs/comment

---

lua/fzf-lua/previewer/codeaction.lua

Super nit, but given that this message is displayed in the preview window of non-previewable code actions I couldn't resist :D

fix(lsp_code_actions): typo in preview message

---

lua/fzf-lua/core.lua

I want to add two custom actions `switch_provider` and `switch_cwd` and have them shown in the fzf header like what the `live_grep` or the `git_status` provider has:
```lua
---Switch provider while preserving the last query and cwd
---@return nil
local function switch_provider()
local opts = {
query = fzf.config.__resume_data.last_query,
cwd = fzf.config.__resume_data.opts.cwd,
}
fzf.builtin({
actions = {
['default'] = function(selected)
fzf[selected[1]](opts)
end,
['esc'] = function()
fzf.resume(opts)
end,
},
})
end
---Switch cwd while preserving the last query
---@return nil
local function switch_cwd()
local opts = fzf.config.__resume_data.opts or {}
-- Remove old fn_selected, else selected item will be opened
-- with previous cwd
opts.fn_selected = nil
opts.cwd = opts.cwd or …
```

feat: expose core.ACTION_DEFINITIONS to allow custom header sections

---

lua/fzf-lua/providers/oldfiles.lua

At the moment, when the `include_current_session` option is enabled, extra files get into the oldfiles list (for example, files that got into the preview, but were not opened). It seems that only those files that were actually opened by the user should be added to oldfiles.

fix(oldfiles): exclude unlisted buffers

---

lua/fzf-lua/utils.lua

... so that `require("fzf-lua.utils").fzf_version()` can work, no need
to call like `require("fzf-lua.utils").fzf_version({})`.

fix: make `opts` optional in `fzf-lua.utils.fzf_version`

---

lua/fzf-lua/init.lua
lua/fzf-lua/utils.lua

Use the new `vim.system()` API on neovim 0.10 or higher, in place of
`vim.fn.system()`. It's more performant by using libuv (`vim.loop`),
though only slightly and known to have less glitches.

refactor(utils)!: use vim.system for running process if available

---

lua/fzf-lua/providers/buffers.lua

See discussion in #1000.
Since *NIX file names allow any character, using them as is in an entry can break tabs functionality. The solution is to encode them in base64 and use a separator that is not in the base64 table, such as colon.
To decode the directory name, Neovim itself can be used:
```lua
fzf.tabs({
fzf_opts = {
["--preview"] = [['echo -n "Tab #"{1}": "; nvim -u NONE -es +":verbose lua print(vim.base64.decode({2}))"']],
["--preview-window"] = "up,1",
}
})
```
Or one can use `base64`:
```lua
fzf.tabs({
fzf_opts = {
["--preview"] = [['echo "Tab #"{1}": $(echo {2} | base64 -d -)"']],
["--preview-window"] = "up,1",
}
})
```

Encode tab_cwd in base64 (*NIX file names are permissive)

---

lua/fzf-lua/defaults.lua
lua/fzf-lua/providers/nvim.lua

I noticed that the default values weren't set and calling `normalize_opts` was missing for the `changes` builtin. This was causing issues when I was trying to override the prompt in my configuration. I've updated the defaults, please let me know if any other changes are needed.

fix(changes): add defaults values for changes

---

lua/fzf-lua/win.lua

If we're using fzf-lua with the split option the default behavior is that after leaving the fzf window the remaining windows will be balanced in size (`CTRL-W_=`). I would argue that the default should be to restore the previous layout which the user might have configured to their liking (the floating window also does not interfere with the window layout).
> using `sh -c "$(curl -s https://raw.githubusercontent.com/ibhagwan/fzf-lua/main/scripts/mini.sh)"`
- split the window (`:split`)
- adapt the height of the current window (e.g. `CTRL-W_+`)
- configure fzf-lua to use the split option `:lua require'fzf-lua'.setup { winopts = { split = 'botright new' }}`
- open a file via fzf `:FzfLua files`
The window sizes are restored to their values before invoking fzf-lua
All windows have been …

fix: restore window layout for splits

---

lua/fzf-lua/actions.lua

`toggle-ignore` action always resets cwd to the current working directory, this PR fixes the issue.

fix(actions): toggle-ignore not preserving cwd

---

lua/fzf-lua/core.lua

Currently when fzf_opts["--preview-window"] is set to false, it works as long as opts.preview_offset is not set. But this is set for grep by default so it throws error. This checks if --preview-window is set before adding preview offset to it.

Allow setting --preview-window to false to not override FZF defaults

---

lua/fzf-lua/actions.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/previewer/fzf.lua
lua/fzf-lua/providers/manpages.lua

The man pages are grouped into different sections and it is common for identically named pages to be found in multiple sections. For instance `printf(1)` documenting the shell command and `printf(3)` documenting the C-function.
Prior to these changes the section name was stripped away from the selected entries, so it only previews and opens that page from the default section even though another section was selected. Now the apropos entry is rewritten to a `:Man` argument with the section name.

fix(manpages): preview and open the correct section for the man page

---

README.md
lua/fzf-lua/defaults.lua
lua/fzf-lua/providers/quickfix.lua

So that the quickfix/loclist providers can include less noise to begin with if users prefers that. Much like the `:clist` command that you need to add a bang to for it to include the invalid entries.

feat(quickfix): add an only_valid option

---

lua/fzf-lua/providers/quickfix.lua

That means having them displayed without new lines so that they are concatenated into on one long line. Prior to these changes if a quickfix entry included newlines those would become separate entries in the fzf selection list. Quickfix entries are formatted so they start with the file name and location, but only the first line is like that, so if one were to select one of the other lines from an entry the start of this line would be interpreted as a file name and would open a buffer "there"
Here is an example of a multiline error (not really a realistic one as it does not have a filename to begin with though), before:
After:

fix(quickfix): handle multi-line entries more like the quicklist window

---

lua/fzf-lua/core.lua
lua/fzf-lua/win.lua

The split mode opens the fzf selection in a split from the current window, so the number of available columns can be less than the width of the full terminal, which should be taken into the account when calculating whether the width exceeds the flex threshold or not.
As discussed in #1040, fzf-tmux also have a split mode, in which case the split is relative to the full-width of the terminal window, so maybe the `fzf_bin` should also be taken into account here. Or maybe it should not because fzf-tmux only takes effect if the terminal is a tmux session (or maybe also check e.g. `vim.env.TMUX` to determine if fzf-tmux would have an effect). However, whilst testing that it turns out that having split mode set with fzf-tmux in a tmux session has a lot more serious issues. The behavior on my …

fix(preview): set flex threshold from window columns in split mode

---

lua/fzf-lua/config.lua
lua/fzf-lua/win.lua

In case the tmux terminal is vertically split already, because then the pane will be split from the current pane not the full window width.

fix(fzf-tmux): get flex layout for split panes from vim width

---

lua/fzf-lua/config.lua

Because for some reason the selection result does not have any effect when both are configured in and you are in a tmux session.
> I’m failing to imagine how these options work together at all, IMHO if someone is using fzf-tmux and tmux env exists, split should be disabled.
Yes, that seems to solve the problem, so that is probably better than to just leave it as is.

fix(fzf-tmux): disable split mode when using fzf-tmux in a tmux session

---

lua/fzf-lua/providers/diagnostic.lua

For example, I have this in my config.
```
vim.diagnostic.config {
signs = { severity = { min = vim.diagnostic.severity.WARN } },
}
```

fix(diagnostic): sign config may not have text

---

lua/fzf-lua/actions.lua

I think I might have found a bug here. Basically if you pass in or transform (with `opts._fmt.from`) a quickfix entry into a uri you can end up getting a broken quickfix list entry that won't open the buffer you want when selected.
1. Trigger [sel_to_qf](https://github.com/milogert/fzf-lua/blob/e5380beb412b6024364544de3e64bd7af107e48f/lua/fzf-lua/actions.lua#L193-L193) with an entry list that looks like `{ "octo://ibhagwan/fzf-lua/issues/1098" }`
2. That calls [path.entry_to_file](https://github.com/milogert/fzf-lua/blob/e5380beb412b6024364544de3e64bd7af107e48f/lua/fzf-lua/path.lua#L372-L372)
3. On https://github.com/milogert/fzf-lua/blob/e5380beb412b6024364544de3e64bd7af107e48f/lua/fzf-lua/path.lua#L396-L396 it will determine that it _is_ a URI and also doesn't not have a `bufnr`.
4. …

fix: use uri as filename for quickfix list

---

autoload/fzf_lua.vim
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/providers/buffers.lua
lua/fzf-lua/utils.lua
lua/fzf-lua/win.lua

Context:
I noticed that `:FzfLua buffers` gets very slow and uses gigabytes of memory after I explore a directory with many files with [fern.vim](https://github.com/lambdalisue/fern.vim). After some investigation, I found out that
* the most of the time is spent converting vim value to lua value (`encode_vim_to_lua`)
* fzf-lua unintentionally loads buffer variables with `vim.fn.getbufinfo`
* fern stores the directory structure in buffer variable, which is cyclic due to reference to the parent node
* converting vim values containing cycles to lua value seems to exhibit time/space complexity that is quadratic on the degree of the graph node.
---
Problem:
Calling vim.fn.{getbufinfo,getwininfo} in lua can be slow because it has to convert potentially big and cyclic data structures stored in …

perf: avoid copying buffer/window variables to lua

---

README.md
lua/fzf-lua/providers/nvim.lua

This PR, addresses two things one is a bug, where if you defined a mark inside your config file and it was not present in nvim at the moment of the search it would throw an error, the second one is the usage of lua patterns to match the marks and make it more user friendly to filter unwanted marks:
```lua
-- the culprit is this call:
vim.fn.execute("marks %s")
```
As of now the logic for filtering is to put a string of individual characters, to match only the marks you wan't, this works, but if you need a more complex solution your config file may end up like this:
When instead it could look like this:
And finally here's an example of the feature in action:

feat: Filter marks with regex string

---

README.md
lua/fzf-lua/defaults.lua
lua/fzf-lua/init.lua
lua/fzf-lua/make_entry.lua
lua/fzf-lua/providers/buffers.lua

New highlight customization requested in discussion #1153, `FzfLuaPathLineNr` and `FzfLuaPathColNr`.
Used in the below pickers:
- buffers
- tabs
- lines|blines
- lsp
- diagnostics
- quickfix|loclist

feat(highlights)!: new hlgroups for paths line|col

---

.luarc.jsonc
OPTIONS.md
README.md
doc/fzf-lua-opts.txt
lua/fzf-lua/cmd.lua
lua/fzf-lua/cmp_src.lua
lua/fzf-lua/config.lua
lua/fzf-lua/defaults.lua
lua/fzf-lua/init.lua
lua/fzf-lua/profiles/borderless.lua
lua/fzf-lua/profiles/borderless_full.lua
lua/fzf-lua/win.lua
plugin/fzf-lua.lua
plugin/fzf-lua.vim

- Documented most of fzf-lua options in "OPTIONS.md"
- Auto-generate "options.txt" vimdoc help file
- Custom `cmp-cmdline` source for `:FzfLua` user command
- Includes cmp docs for all fzf-lua pickers and options
- Auto-inject cmp source when available

feat: nvim-cmp source for `:FzfLua` completion (+docs)

---

lua/fzf-lua/core.lua

Hi, Thanks for a great plugin!
I've been customizing it based on [this page](https://github.com/ibhagwan/fzf-lua/wiki/Advanced), but the annotations in `fzf_exec` seem to be wrong and I want to fix it.
I get ls warnings for fields that should be omissible.
Also, `fzf_live` does not have annotation, so I need to add it.
However, I am concerned that opts is inherently a more complex table.
Should I do it this way? I'm willing to do that work, but where is the list of all the fields?
```lua
---@class fzf_exec_opts
---@field cwd? string
---@field prompt? string
...
```

fix: use proper annotations for public APIs

---

lua/fzf-lua/core.lua

If my perception is wrong, please point it out.
- An entry is string or number (just need to be able to apply `table.concat()`).
- `fzf_cb` can receive a callback function as a second argument (optional).

fix: annotaion for fzf_exec

---

lua/fzf-lua/win.lua

Currently, it's not possible to set a proper description for an action of the form `{ fn = function()end, prefix = ""}`
This PR adds support for getting the action description from the `fn` or if set fom `action.desc`
To be clear, this is for keymap help from something like:
```lua
config.defaults.actions.files["ctrl-t"] = require("trouble.sources.fzf").actions.open -- this is an action table
```

fix: allow setting help str for action tables and/or action.fn

---

lua/fzf-lua/win.lua

I noticed that the position of the floating window was not completely centered using the config below:
```lua
winopts = {
width = 0.8,
height = 0.8,
row = 0.5,
col = 0.5,
},
```
This PR fixes that.
Initially I thought it was because the border wasn't taken into account, but it isn't.
With the PR the window is now correctly centered with/without borders.

fix(win): take border width into account when calculating fractional position

---

lua/fzf-lua/core.lua

To reproduce the bug:
```lua
require("fzf-lua").setup { keymap = { fzf = {} } }
```
then `:FzfLua builtin<cr>` cannot open the float windows.

fix: when bind is nil

---

lua/fzf-lua/providers/colorschemes.lua

Similar to helptags, I added colorschemes for unloaded plugins.
Lazy also automatically loads a colorscheme plugin when it's not loaded yet, so that works ootb.

feat: include colorschemes from unloaded lazy plugins

---

README.md

`*after*` would misguide `:helptags` to pick it up as a tag e.g. `:h after`.

readme: use underscore for emphasis

---

lua/fzf-lua/providers/lsp.lua

`gd` on java class files results in error (as shown below) after the recent addition of the workaround for #1317. This is because when jumping to, for example, `java.lang.String` class, jdtls would use a URI in this format: `jdt://contents/java.base/java.lang/String.class...`
The workaround would add `file://` unless the URI matches `file://` and therefore would change the `jdt://...` into `file://jdt://...`. This PR is to make the workaround to prepend `file://` only if the string is not a URI.
Error message before PR change:
```
Error executing Lua callback: .../share/nvim/lazy/lazy.nvim/lua/lazy/core/handler/cmd.lua:48: Vim:Error executing Lua callback: /usr/share/nvim/runtime/lua/vim/lsp/util.lua:1914: index out of range
stack traceback:
[C]: in function '_str_byteindex_enc' …
```

fix(lsp): do not prepend `file://` for URIs

---

lua/fzf-lua/core.lua

fzf-lua's config
```lua
require("fzf-lua").setup {
actions = { files = { ["ctrl-x"] = { fn = function() end, reload = true } } },
}
```
Then run `:FzfLua live_grep query=acceptxx debug=true<cr>` will fail.
```
[Fzf-lua]: FZF_DEFAULT_COMMAND: VIMRUNTIME='/usr/share/nvim/runtime' '/usr/bin/nvim' -n --headless --clean --cmd 'lua vim.g.did_load_filetypes=1; loadfile([[/tmp/fzf-lua.tmp/nvim/site/pack/vendor/start/fzf-lua/lua/fzf-lua/libuv.lua]])().spawn_stdio([==[e2RlYnVnID0gdHJ1ZSwgY21kID0gInJnIC0tY29sdW1uIC0tbGluZS1udW1iZXIgLS1uby1oZWFkaW5nIC0tY29sb3I9YWx3YXlzIC0tc21hcnQtY2FzZSAtLW1heC1jb2x1bW5zPTQwOTYgLWUge2FyZ3Z6fSAiLCBnaXRfaWNvbnMgPSBmYWxzZSwgY29sb3JfaWNvbnMgPSB0cnVlLCBnID0ge19memZfbHVhX3NlcnZlciA9ICIvcnVuL3VzZXIvMTAwMC9memYtbHVhLjE3MjEwNjE4NjYuMTMyNDM5LjEiLCBfZGV2aWNvbnNfcGF0aCA9ICIvdG1wL …
```

fix: don't replace "accept" in normal query

---

lua/fzf-lua/actions.lua

This PR ensures a lazy plugin is loaded before trying to show its helptags.
Fixes #1342

fix(helptags): make surethe plugin is loaded when showing helptags

---

lua/fzf-lua/win.lua

This fixes the previewer not respecting the provided zindex, leading to the main window working as intended while the previewer occluded other windows that overlap it (for example, in my case at least, the ``noice.nvim`` command popup was being mostly occluded by the previewer window with only a small portion being visible).
I made these changes pretty quickly and I'm not really familiar with the code-base, so I'd appreciate if someone with more knowledge on how the project works could make sure these changes won't cause any weird edge-cases or visual bugs. I don't think it'll cause any issue but I thought it still worth mentioning.

fix(previewer): respect zindex

---

README.md
lua/fzf-lua/core.lua
lua/fzf-lua/defaults.lua
lua/fzf-lua/init.lua
lua/fzf-lua/win.lua

Notes:
- Default bind for hiding set to `<M-Esc>` (i.e. "alt-escape")
- Can be set to any other Neovim-style key in `keymap.builtin` setting the value to "hide"
- `:FzfLua resume` will prioritize an open window vs starting a a new fzf process with the same arguments
- Does not (and cannot) work with fzf-tmux as there are no neovim buffers to store (everything is an external process)
Closes #1229

feat(UI): fzf window hide/unhide (closes #1229)

---

lua/fzf-lua/previewer/builtin.lua

If no tag is found (e.g. the user typed a prompt that no longer shows any results), the following line throws an error
https://github.com/TheLeoP/fzf-lua/blob/af659d93df1b110967f5a41e86b969fbabf858a7/lua/fzf-lua/previewer/builtin.lua#L980
Instad, this PR returns an empty table early if no tag is found

fix(help-previewer): don't error if no table is found

---

lua/fzf-lua/providers/lsp.lua

For example, use `require("fzf-lua").lsp_references`
with `opts.unique_line_items = true`:
with `opts.unique_line_items = false`:
> This can also be a workaround for https://github.com/LuaLS/lua-language-server/issues/2451.

feat(lsp): add `unique_line_items` options

---

lua/fzf-lua/fzf.lua
lua/fzf-lua/libuv.lua

MSYS2 comes with "/usr/bin/cmd", to avoid conflicts we specifically use "cmd.exe".

fix(windows): fully qualify "cmd.exe" (closes #1396)

---

README.md
lua/fzf-lua/actions.lua
lua/fzf-lua/config.lua
lua/fzf-lua/core.lua
lua/fzf-lua/defaults.lua
lua/fzf-lua/path.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/previewer/fzf.lua
lua/fzf-lua/profiles/fzf-vim.lua
lua/fzf-lua/profiles/telescope.lua
lua/fzf-lua/providers/files.lua
lua/fzf-lua/providers/lsp.lua

Not really breaking but requires attention if you care for setup options improvement.
All entries whether file or buffer can now utilize the same actions code, previously buffer actions (e.g. `buf_edit`) are not mapped to file actions (e.g. `file_edit`) and can work on any file-buffer entry.
Setup's `actions.files` is now used for all file-buffer pickers which simplifies setting up default actions.
**NOTE:** For backward compat previously defined `actions.buffers` will still be used and will take precedence over `actions.files` for buffer pickers (buffers, tabs, lines, blines).
Additional changes:
- Default bind for sending to location list changed from "alt-l" to "alt-Q" ("alt-shift-Q", doesn't work with skim).
- Default actions changed from `default` to `enter` to match fzf's …

refactor(actions)!: join `{buf|file}_xxx` actions

---

lua/fzf-lua/providers/oldfiles.lua

This allows reopening buffers that were first opened in the current session, and then closed again.
Steps to reproduce:
1. Open a buffer which doesn't appear in `oldfiles` yet
2. Close it with `:bd`
3. Run `:FzfLua oldfiles` (with `include_current_session` enabled)
4. Previously the closed buffer wouldn't show up, but now it does! :tada:

fix(oldfiles): include unlisted buffers with `include_current_session`

---

lua/fzf-lua/actions.lua

Hey @ibhagwan!
I planned to open and issue to discuss this, but it was a simple enough change that I decided to just do it. I don't know if you used `input` deliberately instead of `confirm`, but I think overall `confirm` is in the changed cases. It requires one less keystroke, and it looks nicer if you use a GUI or TUI like Noice. I kept the `Yes`/`No` combo, so there's no need to learn new keystrokes.
And while I was here, I also wrapped the `drop` action with confirm, as it's destructive (even when most of the time you can recover things using the reflog)

refactor: use confirm instead of input where it makes sense

---

lua/fzf-lua/defaults.lua
lua/fzf-lua/providers/buffers.lua

Tab indices are used in ex commands (e.g. `:tabn`) and are more human friendly:
```lua
fzf.tabs({
fzf_opts = {
["--preview"] = [['echo "Tab #"{1}": $(echo {2} | base64 -d -)"']],
["--preview-window"] = "nohidden:up,1",
}
})
```

Tab index also embedded in buffer entry

---

lua/fzf-lua/actions.lua

Hi, I noticed when I have a buffer list open with a single buffer, calling file_switch_or_edit buffer results in some error due to the passed arg doesn't have any selected buffer.
I added a line to prevent file_switch function from producing error and instead to simply return false
Thank you,

fix: file_switch_or_edit with nill

---

lua/fzf-lua/providers/nvim.lua

`:cle<cr>`, `:FzfLua jumps<cr>`
(or: `:delm!<cr>`, `:FzfLua changes<cr>`)
```
Error executing vim.schedule lua callback: ...hare/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:1118: attempt to perform arithmetic on a nil value
stack traceback:
...hare/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:1118: in function 'parse_entry'
...hare/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:605: in function 'populate_preview_buf'
...hare/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:263: in function 'populate_preview_buf'
...hare/nvim/lazy/fzf-lua/lua/fzf-lua/previewer/builtin.lua:280: in function ''
vim/_editor.lua: in function ''
vim/_editor.lua: in function <vim/_editor.lua:0>
```

fix: when jumplist or changelist is nil

---

lua/fzf-lua/config.lua

I'm trying to attach [`dropbar.nvim`](https://github.com/Bekaboo/dropbar.nvim/) to the preview buffer. And I want to attach only on pickers like `grep/lsp_definitions` but not `files`, so with this pr it can be done by:
```lua
require('fzf-lua').setup {
winopts_fn = function(opts)
return {
preview = {
winopts = {
winbar = opts.winopts.preview.winopts.cursorline
and '%{%v:lua.dropbar.get_dropbar_str()%}'
or nil,
},
},
}
end,
}
```
BTW, actually before that I also try to use `autocmds` on the preview win/buf open, or use `after/ftplugins` to detect it, but both didn't work. I found the root cause is `eventignore` from this commit: https://github.com/ibhagwan/fzf-lua/commit/6be3ba4620ed44b29abc1562ecf67e4fdfb48d20. And it can be noted that `w:fzf_lua_preview` here may never be used, since …

feat(winopts): pass current opts to `winopts_fn`

---

README.md
lua/fzf-lua/defaults.lua
lua/fzf-lua/providers/nvim.lua

Hi, thanks for this package!
I'm migrating from the telescope (because of slowness on large codebases), and I noticed that the keymaps picker is too restrictive, which is not very useful for those who provide detailed descriptions for all bindings:
This PR introduces the `show_details` option, which (if `false`) disables the `detail` column completely and shows this info only if `description` is empty.
By default, `show_details = true`, thus it doesn't affect existing users.
Result:

feat(keymaps): add the `show_details` option

---

lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/utils.lua

Due to a recent treesitter breaking change on neovim.
`vim.treesitter.language.add` returns `true` or `nil, error` now. thus can use it directly without `pcall`.
see https://github.com/neovim/neovim/pull/30379

feat: adopt upstream treesitter breaking change

---

lua/fzf-lua/init.lua

Remove `hide/unhide` entry from the builtin picker (I think they are useless here).

fix: remove useless `{un,}hide` from builtin picker

---

README.md

The command is mentioned twice, but the second mention should be `grep_loclist`

Fix duplicate `grep_quickfix` in README

---

lua/fzf-lua/actions.lua
lua/fzf-lua/defaults.lua
lua/fzf-lua/path.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/providers/lsp.lua

`vim.lsp.util.jump_to_location` was deprecated in https://github.com/neovim/neovim/pull/30877.
This PR replaces its uses by `vim.lsp.show_document` (which `jump_to_location` uses in its implementation).

fix(lsp): vim.lsp.util.jump_to_location is now deprecated

---

lua/fzf-lua/actions.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/providers/lsp.lua
lua/fzf-lua/utils.lua

Follow up of #1503 to preserve backwards compatibility with versions 5-9.

fix(lsp): preserve backwards compatibility with jump_to_location deprecation

---

lua/fzf-lua/providers/lsp.lua

Adapt to the upstream change https://github.com/neovim/neovim/commit/629483e24eed3f2c07e55e0540c553361e0345a2 to get rid of the warning message "warning: offset_encoding is required, using the offset_encoding from the first client".

fix: offset_encoding is required now in `make_position_params` and `make_range_params`

---

lua/fzf-lua/providers/colorschemes.lua

Currently, running `:FzfLua highlights` doesn't actually do *anything* when an entry is selected.
I think it is logical to display the highlighted group in the command line as if `:hi <group>` was run.

Display Selected Highlight Group In Colorscheme Provider

---

lua/fzf-lua/actions.lua
lua/fzf-lua/make_entry.lua
lua/fzf-lua/previewer/builtin.lua

Attempts to fix the problems highlighted in [this issue](https://github.com/ibhagwan/fzf-lua/issues/1547), notably:
- the line number of tag entries with no regex was not properly extracted, and thus were unusable
- tag entries with both a regex and a line number did not take advantage of the line number, thus were susceptible to collisions on the regex
-   the default previewer for tags could not make use of the line number of an entry

fix(ctag): better handle line number for tag entries

---

OPTIONS.md
doc/fzf-lua-opts.txt
lua/fzf-lua/win.lua

**Feedback appreciated**: https://github.com/ibhagwan/fzf-lua/issues/1485
Will only work with file-like entries, e.g. grep_xxx, blines, etc:
```
file:line:col:text   (grep_xxx)
file:line:text       (grep_project or missing "--column" flag)
line:col:text        (grep_curbuf)
line:text            (blines)
```
Enable globally via `setup`:
```lua
require("fzf-lua").setup({ winopts = { treesitter = true } })
```
Or call individually per picker:
```vim
:FzfLua blines winopts.treesitter=true
```
or
```lua
:lua require("fzf-lua").blines({ winopts = { treesitter = true } })
```

feat(beta): use ts highlights in main fzf win

---

lua/fzf-lua/actions.lua

When a custom formatter is used the `file_switch` action along with any other that depend on it are never able to resolve to an existing buffer.
This is because the call that resolves a selected entry to a file does not provide options so the entry resolution does not know a formatter was used.

fix(actions): file_switch with formatter

---

lua/fzf-lua/actions.lua

It looks like a Lua gotcha, 0 is truthy. When the line information is absent in the tags file, the search behavior isn’t available.
Using an example file `foo.py`:
```python
def main():
pass
def foo():
pass
```
I generate my ctags with:
```
ctags --tag-relative=yes -f"tags" foo.py
```
That gives the following entries (without headers), which do not contains line numbers:
```
foo	toto.py	/^def foo():$/;"	f
main	toto.py	/^def main():$/;"	f
```
When the action runs, the line information is `0`, so the check `if entry.ctags and not entry.line` is not entered.

fix(tags): Restore searching for tag when line is not in ctags

---

lua/fzf-lua/previewer/builtin.lua

1. Launch live_grep in `fzf-lua` repo, paste/type `vim.api.nvim_win_call, self.border_winid`.
2. Then type: `x`.
Nothing matched, but treesitter context window remain open.

fix(previewer): treesitter-context not closed in `live_grep`

---

OPTIONS.md
README.md
doc/fzf-lua-opts.txt
lua/fzf-lua/config.lua
lua/fzf-lua/core.lua
lua/fzf-lua/defaults.lua
lua/fzf-lua/init.lua
lua/fzf-lua/lib/utf8.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/profiles/default-title.lua
lua/fzf-lua/profiles/fzf-tmux.lua
lua/fzf-lua/profiles/telescope.lua
lua/fzf-lua/providers/buffers.lua
lua/fzf-lua/providers/grep.lua
lua/fzf-lua/providers/helptags.lua
lua/fzf-lua/win.lua

Semi-breaking (backward compat): builtin previewer `enable = ...` options renamed to `enabled = ...` for consistency with other plugins conventions:
- previewers.builtin.treesitter.enable -> enabled
- previewers.builtin.treesitter.disable -> disabled
- previewers.builtin.render_markdown.enable -> enabled
Warning messages will be sent to the message log about old deprecated options (old ones too), can be disabled with `silent=true`:
```lua
require("fzf-lua").setup({ defaults = { silent = true } })
```
This commits also includes many other changes:
- `winopts.treesitter` can also be enabled (disabled by default) in grep/LSP pickers, but will be disabled in `live_grep` as ts highlights will override the regex highlighting
- When enabled `fzf_colors` will automatically set `hl,hl+` to …

feat(treesitter)!: enable treesitter for `lines|blines|git_blame`

---

lua/fzf-lua/previewer/builtin.lua

Scroll means `preview-page-down`/`preview-page-up` here.

fix: scroll report error on fzf match nothing

---

lua/fzf-lua/config.lua
lua/fzf-lua/core.lua
lua/fzf-lua/profiles/skim.lua

Will remove any non-compat options from `fzf_opts`.
For exmaple, having `["--no-scrollbar"] = true` will fail on skim and any fzf version below 0.36.
ref: https://github.com/LazyVim/LazyVim/issues/5193
By default compat warnings are supressed unless `compat_warn=true`, for example running:
```vim
:FzfLua files fzf_bin=sk compat_warn=true
```
Will result in:
Or if running an older fzf version:
```vim
:FzfLua files fzf_bin=~/Downloads/fzf/fzf-0.25.0 compat_warn=true
```

feat: auto remove non-compat flags from fzf/skim

---

lua/fzf-lua/core.lua

I think this is right, matching the type of `fn_reload` in `fzf_exec`.

fix: type of `fzf_live` param

---

lua/fzf-lua/providers/nvim.lua

The headers of `search_history` and `command_history` are always set to `:: <CR> to execute, <Ctrl-e> to edit` despite custom configs, for example, users can disable `ctrl-e` for its original purpose (move cursor to the end of prompt). This PR dynamically set the header using `core.set_header()`.

fix: `search_history` and `command_history` not showing custom actions

---

lua/fzf-lua/providers/nvim.lua

**Problem:**
If the builtin command description spans multiple lines, only the first line is captured and showed and the remaining lines won't be matched. I believe the issue lies in mistakenly writing `+` as `%+` in the regex.
**Solution:**
Correct the regex in `string.match()` and properly prepend a whitespace when concatenating multiple lines.

fix: multi-line command desc not captured properly

---

lua/fzf-lua/previewer/builtin.lua

Original issue: https://github.com/ibhagwan/fzf-lua/issues/1641
https://github.com/ibhagwan/fzf-lua/commit/7307943791d7531a8a04f6ccbc5ac8e3292ea467 did not work for me.

fix(previewer): regex escape --fixed-strings

---

README.md

I have seen [this comment](https://www.reddit.com/r/neovim/comments/1hgvt7c/comment/m2nvwxx/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) of yours on reddit and have decided to come up with a proposal to help you clear up the docs. Let me try to explain the rationale of this PR before you get a heart attack by looking at the diff :D 
I have been a long-term Fzf-lua user and more or less know my way around this project, in the sense that I know where to find information I need; however, I sometimes do struggle navigating through the README, the Wiki and the issues just because of course there are so many options and contributions and it is hard to have a unified glance. For this reason I have proposed a strong refactoring of the README based on …

refactoring of README.md

---

lua/fzf-lua/fzf.lua
lua/fzf-lua/utils.lua

Utilize the `ModeChanged` event to enter TERMINAL mode from NORMAL TERMINAL mode instead of the current approach which tested the mode after the job started, since mode changes are scheduled in neovim the former was bound to fail in some cases as demonstrated in #1657.
Still keeps the old approach for neovim < 0.7 as both `ModeChanged` and "normal terminal" mode didn't exist prior to that. I should probaly bump the min neovim version to 0.7 at least but what's the harm of keeping a few extra lines for supporting old versions?
This commit also fixes another bug which mapped `<C-c>` to `<Esc>` on the origin buffer when using `fzf-tmux` and removes the `<C-c>` workaround for https://github.com/neovim/neovim/issues/20726 to neovim >= v0.10.2 (previously was just removed in 0.11) - this should …

fix: new approach to NORMAL TERMINAL mode (#1657)

---

lua/fzf-lua/providers/lsp.lua

`fzf_lsp_locations` was making an access to a nil value, for example when calling `lsp_incoming_calls` on a element that does not have any incoming calls.

fix(lsp): fix invalid access in `fzf_lsp_locations`

---

lua/fzf-lua/actions.lua

https://github.com/ibhagwan/fzf-lua/issues/1696
This adds support to closing buffers using `buf_del` (`<C-x>`) for unsaved buffers as well. The current version only supports closing "clean" buffers.
It uses `utils.save_dialog` to confirm closing an unsaved buffer.
Let me know if there is anything that I missed or can be improved. Thank you!

Feat: enable closing dirty buffer

---

lua/fzf-lua/utils.lua

1. Open some buffers and make an unsaved change in one
2. `:LazyLua buffers`
3. Attempt to close the unsaved buffer in the picker (default bind is `<C-x>`)
4. Press `<Esc>` or `<C-c>` when the save dialog appears
5. Note that the buffer force closes without saving instead of canceling the save dialog
A followup to #1697
I noticed that pressing `<Esc>` or `<C-c>` does not cancel on the buffer save dialog from `utils.save_dialog`. 
This is because `vim.fn.confirm()` returns `0` on `<Esc>` or `<C-c>` and `utils.save_dialog` does not account for a `0` case currently, so it reaches the final `return true` statement.
Neovim doc for `vim.fn.confirm()`: https://neovim.io/doc/user/builtin.html#confirm()

Fix: Press Esc on buffer save dialog to cancel

---

lua/fzf-lua/previewer/builtin.lua

Issues this commit is trying to solve,
- Removes any extra logical checks that may lead to performance loss(mostly caused by `markview.clean()`).
- Removes any need to listen to events or mode changes for preview buffers(preview buffers are assumed to be *immutable*).
- Only renders once per file during an active `:FzfLua` session.
- Disables previewing when line count exceeds the configured `max_buf_lines` in markview(See the comments in the commit on how to manually set it).
> After weighing the pros & cons of partially rendering on the preview the cons out-weight the pros.

fix: Use `strict_render` to reduce the number of times things get drawn

---

lua/fzf-lua/providers/helptags.lua

Native lua `string.format` cannot handle multi-byte char
Related: https://github.com/ibhagwan/fzf-lua/issues/1417
Before:
Now:

fix(helptags): handle multibyte char align

---

lua/fzf-lua/config.lua
lua/fzf-lua/core.lua
lua/fzf-lua/devicons.lua
lua/fzf-lua/init.lua
lua/fzf-lua/libuv.lua
lua/fzf-lua/make_entry.lua
lua/fzf-lua/providers/git.lua
lua/fzf-lua/providers/tags.lua
lua/fzf-lua/shell.lua
lua/fzf-lua/spawn.lua
scripts/headless_fd.sh
tests/devicons_spec.lua
tests/minicons.spec.lua

Was using `--clean` which wasn't disabling nvim plugins, this had some rare side effects with netrw.
Other changes:
- Separated the spawn code to its own lua script and eliminating the need to test if running headless.
- Eliminated the `require` hack by going up one more level in the the `package.path` prefix
- Using `_G` instead of `vim.g` for global `fzf_lua_is_headless` in case we decide one day to use `nvim -ll` which doesn't have access to `vim.g`
ref: #1717

refactor: spawn headless instances using `-u NONE -i NONE`

---

lua/fzf-lua/win.lua

Would be great to resume scroll postion when resume after hide?
* related: https://github.com/ibhagwan/fzf-lua/issues/1686

feat(hide): keep scroll position

---

lua/fzf-lua/core.lua
lua/fzf-lua/fzf.lua
lua/fzf-lua/init.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/providers/colorschemes.lua
lua/fzf-lua/providers/lsp.lua
lua/fzf-lua/shell.lua
lua/fzf-lua/shell_helper.lua
lua/fzf-lua/utils.lua

* legacy `opts.preview_window` -> `fzf_opts.--preview_window`
* `vim.fn.termopen` -> `vim.fn.jobstart` + `{ term = true }`
* `vim.loop` -> `vim.uv`
* `vim.lsp.diagnostics.get_line_diagnostics` -> `vim.lsp.diagnostic.get`
* remove term workaround 9a755f225bc6 (fixed now)
* `opts.silent` when `reload` fallback to `resume`

chore: cleanup deprecated things

---

README.md
lua/fzf-lua/actions.lua
lua/fzf-lua/config.lua
lua/fzf-lua/core.lua
lua/fzf-lua/defaults.lua
lua/fzf-lua/init.lua
lua/fzf-lua/profiles/README.md
lua/fzf-lua/profiles/hide.lua
lua/fzf-lua/providers/colorschemes.lua
lua/fzf-lua/providers/module.lua
lua/fzf-lua/providers/ui_select.lua
lua/fzf-lua/shell.lua
lua/fzf-lua/utils.lua
lua/fzf-lua/win.lua

The profile changes the default binds to hide the fzf-lua window instead of aborting it, therefore keeping cursor position, selection, etc.
Note that this also continues long running operations in the background so be mindful of sending fzf to background on a large mono repo, can still be aborted with `ctrl-c` or `alt-esc`.
Enable with:
```lua
-- Set as base profile
:lua require("fzf-lua").setup({"hide"})
-- More than one profile
:lua require("fzf-lua").setup({"border-fused","hide"})
-- Or with `profiles`:
:FzfLua profiles load=hide
-- More than one profile
:FzfLua profiles load={"border-fused","hide"}
```

feat(profiles): added `hide` (improved resume, #1686)

---

lua/fzf-lua/profiles/hide.lua
lua/fzf-lua/win.lua

This commit partially reverts 85fa30e.
Extracting last query from the prompt line is problematic, especially with new fzf features such as `--info-command` and `--input-border`.
Instead we call hide instantly (keeping the perf from the old commit) and send <esc> to the terminal to execute the esc action and store the last query using `{q}`.
Closes #1731
Ty @phanen for the `chan_send` idea, worked great with `\x1b` (escape).

fix(hide): better solution for storing last query on esc

---

lua/fzf-lua/defaults.lua

Not sure if this is a issue only happen to me...
```sh
$ man gcc | head
troff:<standard input>:127: warning: cannot select font 'CW'
troff:<standard input>:127: warning: cannot select font 'CW'
troff:<standard input>:128: warning: cannot select font 'CW'
troff:<standard input>:128: warning: cannot select font 'CW'
troff:<standard input>:128: warning: cannot select font 'CW'
troff:<standard input>:129: warning: cannot select font 'CW'
```
And `man -k .` may truncate entries
```sh
man -k . | grep --fixed-strings '... ('
```

fix: improve manpage defaults

---

lua/fzf-lua/shell_helper.lua

Use the following cmd on a large monorepo, typing quickly to ensure fzf kill process before it finished.
```vim
lua require('fzf-lua').fzf_live(function(q) return 'rg ' .. q end)
```
Then notes there're some dangling sockets and tempfiles
```sh
watch -n.1 ls -lh /run/user/1000/nvim*
watch -n.1 ls -lh /tmp/nvim.$USER/
```
* https://github.com/ibhagwan/fzf-lua/issues/329
* https://github.com/neovim/neovim/issues/30123

fix: clean up dangling socket and tempfile for `fzf_live`

---

lua/fzf-lua/utils.lua
lua/fzf-lua/win.lua

After #1721, buffer cache will not be clean after `hide`.
Old scratch buffer need a way to be delete when switching to a different picker.

fix: clean scratch buffer introduced in #1721

---

lua/fzf-lua/previewer/builtin.lua

Fix https://github.com/ibhagwan/fzf-lua/issues/1771.

fix: nvim_buf_get_mark cannot get `'` mark correctly without curwin

---

lua/fzf-lua/actions.lua

Without this patch, spell_apply will throw an exception if no value is selected as it attempts to concatenate a nil value with a string.
Previously: 9226c5a2291ef623ef157e0e1ffea034ffc8b8de

fix: spell_apply with no value selected

---

lua/fzf-lua/previewer/builtin.lua

Since de199f73a54a, garbage collection (0c384eb93f13) stops work for builtin previewer.
Fix by reference `win._previewer` outside, rather than in callback.
Minimal repro:
```lua
local ref
do
local b = require('fzf-lua.utils').setmetatable__gc(
{ a = '4 gc done' },
{ __gc = function(self) print(self.a) end }
)
local tmp_func = function() print(b.a) end
ref = tmp_func
end
-- ref = nil
collectgarbage('collect')
```
gc won't run in this case unless `ref` in explicitly set to nil somewhere, but in our case it's referenced by neovim's api internally...

fix: don't reference `win._previewer` in callback to make gc work

---

scripts/init.lua
scripts/mini.sh

* `$NVIM` is exported to nvim builtin terminal by default on neovim +v0.8.0
* netrw will print errmsg on nightly (https://github.com/neovim/neovim/blob/e08e3d15f66db3fba9f164f0c18b71d72ffb4877/runtime/plugin/netrwPlugin.vim#L7)
```
Error detected while processing /usr/share/nvim/runtime/plugin/netrwPlugin.vim:
line    7:
E919: Directory not found in 'packpath': "pack/*/opt/netrw"
```

chore: update mini.sh

---

lua/fzf-lua/utils.lua

Whenever my `grep` search contained a `@`, I got spammed with a bunch of warning messages on each keystroke. Upon some investigation, I found that a `vim.regex` call made to get the highlight for the current matched line was failing since `@` is a special character for `vim.regex`.
Escape the `@` characters with a `\` before it. This removes the warning messages and adds the highlight matching the query. I tried to limit this to the `vim.regex` call since I noticed there's some custom logic for `--fixed-strings` that is for escaping regex characters to match them explicitly.

fix(grep): allow matching query on line when query contains @

---

lua/fzf-lua/data/colorschemes.json

Was looking through the `colorschemes.json` file and noticed these instances of `darcula`. I'm assuming this is just a typo.
So I just did a simple find and replace.

fix(typo): replace `darcula` with `dracula`

---

lua/fzf-lua/libuv.lua
lua/fzf-lua/shell.lua

Revert https://github.com/ibhagwan/fzf-lua/pull/1743 for two reason:
* This is no longer a problem for nightly (after https://github.com/mrowegawd/neovim/commit/3768fabed0155a04be2937a5f8996c338aedc37b). And this won't happened on any stable nvim.
* 922eff893faf3b32a055298a452eeb08a8a5be00 cause a new issue, it can spam log in another way:
```
ERR 2025-02-08T19:14:51.741 nvim.69567.0/c vim_gettempdir:3494: tempdir disappeared (antivirus or broken cleanup job?): /tmp/nvim.phan/vGwvP7/
ERR 2025-02-08T19:14:51.918 nvim.69567.0/c vim_gettempdir:3494: tempdir disappeared (antivirus or broken cleanup job?): /tmp/nvim.phan/ECnFme/
ERR 2025-02-08T19:14:52.068 nvim.69567.0/c vim_gettempdir:3494: tempdir disappeared (antivirus or broken cleanup job?): /tmp/nvim.phan/D59oYM/
```
Reproduce by
* `tail …

Revert "fix: set TMPDIR for child to avoid lots of logging"

---

lua/fzf-lua/providers/ui_select.lua

Align the numbers in the ui-select function for a cleaner visual effect.
Before:
After:
Test file:
```lua
require('fzf-lua.providers.ui_select').register()
vim.ui.select(
{
'Acai',
'Apple',
'Apricot',
'Asian Pear',
'Avocado',
'Banana',
'Blackberry',
'Blood Orange',
'Blueberry',
'Boysenberry',
'Breadfruit',
'Cactus Pear',
'Cantaloupe',
'Carambola',
'Cherimoya',
'Cherry',
'Clementine',
'Coconut',
'Cranberry',
'Custard Apple',
'Date',
'Dragonfruit',
'Durian',
'Elderberry',
'Fig',
'Gooseberry',
'Grapefruit',
'Grapes',
'Guava',
'Honeydew',
'Jackfruit',
'Jujube',
'Kiwi',
'Kumquat',
'Lemon',
'Lime',
'Lingonberry',
'Loquat',
'Longan',
'Lychee',
'Mandarin',
'Mango',
'Mangosteen',
'Marionberry',
'Mulberry',
'Nectarine',
'Olive',
'Orange',
'Papaya',
'Passion Fruit',
'Peach',
'Pear',
'Persimmon', …
```

feat: align numbers in ui-select function

---

lua/fzf-lua/providers/ui_select.lua

Selected is nil if the number is padded in the ui-select function.
To reproduce: run `:so` in the test file:
```lua
require('fzf-lua.providers.ui_select').register()
vim.ui.select({
'Acai',
'Apple',
'Apricot',
'Asian Pear',
'Avocado',
'Banana',
'Blackberry',
'Blood Orange',
'Blueberry',
'Boysenberry',
'Breadfruit',
'Cactus Pear',
'Cantaloupe',
'Carambola',
'Cherimoya',
'Cherry',
'Clementine',
'Coconut',
'Cranberry',
'Custard Apple',
'Date',
'Dragonfruit',
'Durian',
'Elderberry',
'Fig',
'Gooseberry',
'Grapefruit',
'Grapes',
'Guava',
'Honeydew',
'Jackfruit',
'Jujube',
'Kiwi',
'Kumquat',
'Lemon',
'Lime',
'Lingonberry',
'Loquat',
'Longan',
'Lychee',
'Mandarin',
'Mango',
'Mangosteen',
'Marionberry',
'Mulberry',
'Nectarine',
'Olive',
'Orange',
'Papaya',
'Passion Fruit',
'Peach',
'Pear', …
```

fix: selected is nil if its number is padded

---

lua/fzf-lua/core.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/previewer/codeaction.lua

When trigger actions with no selected entry in hide profile, `selected` always will be `{ "" }`
To reproduce this with `mini.sh`:
* `require('fzf-lua').setup { "hide" }` (or just use `exec_silent = true` actions without this)
* `:FzfLua files cwd=/tmp` 
* typing random thing (ensure no entry selected)
* press enter, then `/tmp` opened in netrw
The root cause is that when use `{q} {+}`, `{+}` is expanded to an empty string if there's no selected entry.
We can use `{n}` to determine if it's really a no-selected case, and then send `{}` to actions rather than `{""}`.

fix: don't send ambiguous empty string when no selected/matched

---

README.md

Hey found a small typo in the README. Thanks!

docs: fix typo for FzfLuaTitleFlags highlight

---

lua/fzf-lua/previewer/codeaction.lua

With `jdtls` there's a space before the code action index, causing the `assert` in the following line to fail.

fix(codeaction): consider whitespace when getting index

---

lua/fzf-lua/providers/lsp.lua

Current logic will actually jump to every location even if there is more than one result.

fix(lsp): correct jump1 logic for call hierarchy

---

lua/fzf-lua/complete.lua

Problem: `require("fzf-lua").complete_file { cwd = vim.fs.root(0, ".git") }` don't work.
Solution: Allow fallback to user passed `opts.cwd`, (higher priority than `uv.cwd()`)

fix(complete): fallback to user provided `opts.cwd`

---

lua/fzf-lua/win.lua

If something in `CTX` changed after picker launched and before picker died (`accept`/or pkilled), then any action may not work as expected.
In "hide" profile, a picker only die when you launch a new picker.
Reproduce with `mini.sh`:
* `:e Makefile`
* `:e README.md`
* open picker (`:FzfLua files`)
* `hide()` then `<c-^>` (or any other way make you navigate to another file, without killing the picker)
* `unhide()` and try to use picker to navigate to `README.md`. But cannot.

fix: update CTX when `unhide`

---

lua/fzf-lua/win.lua

`ctrl-g` in `live_grep` picker should not change layout:
```lua
require('fzf-lua').setup { winopts = { split = 'botright new' } }
```
Did a bisect, this happened after https://github.com/ibhagwan/fzf-lua/commit/d932025a62bc6644cb531e74cf2f1ef35606fd2b..

fix: `ctrl-g` should not change layout when use `live_grep` with `winopts.split`

---

README.md
doc/fzf-lua.txt
lua/fzf-lua/providers/tags.lua

it's = it is
its = possessive form of "it"

fix it's-its grammar mistakes

---

lua/fzf-lua/defaults.lua

`delta` have [osc 10/11 support] support, so it can detect light/dark in
terminal like [kitty,
neovim](https://github.com/bash/terminal-colorsaurus/blob/main/doc/terminal-survey.md),
but sadly not in fzf previewer.
But we can pass a flag to delta using neovim's `&bg` (neovim caculate a
luminance to know if the terminal is dark/light
https://github.com/neovim/neovim/blob/0d5a93be22d27dd095ecbc02775de1f3f4b8d3c9/runtime/lua/vim/_defaults.lua#L776).

feat(defaults): make delta switch dark/light

---

lua/fzf-lua/previewer/builtin.lua

Fix https://github.com/ibhagwan/fzf-lua/discussions/1887

fix: `{q}` may be expanded to nothing rather than `''` on windows

---

lua/fzf-lua/win.lua

Fix https://github.com/ibhagwan/fzf-lua/issues/1907.

fix: force `border = "none"` for scrollbar to ignore `&winborder`

---

lua/fzf-lua/win.lua

Fix https://github.com/ibhagwan/fzf-lua/issues/1907#issuecomment-2745107564.

fix: backdrop shouldn't use `&winborder` too

---

lua/fzf-lua/shell.lua

Fix https://github.com/ibhagwan/fzf-lua/discussions/1901#discussioncomment-12588036.
If pipe is not closed, terminal won't response and refresh unless we
press a ctrl-c.
This can happened when:
```
actions["ctrl-g"].fn = function() error('xxx') end
```

fix: close pipe when actions error

---

lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/utils.lua
lua/fzf-lua/win.lua

See https://github.com/neovim/neovim/issues/33133#issuecomment-2763104765.
Temporally fix https://github.com/ibhagwan/fzf-lua/issues/1929.
*EDIT*: But it didn't handle float win not created by fzf...
* e.g. treesitter.context's win on ctx buffer
* e.g. lsp fidget's spinner win?
Although If you want, you can always override `api.nvim_win_open`,. I think it's usually harmless...

fix: nvim_open_win from ctx win

---

lua/fzf-lua/test/helpers.lua
lua/fzf-lua/utils.lua
scripts/minimal_init.lua
tests/win_spec.lua

In `hide` profile, `:new`, `:FzfLua files`, `<esc>`, `:FzfLua resume`

fix(previewer): `nvim_win_call` fail when `ctx.winid` is invalid

---

lua/fzf-lua/previewer/builtin.lua

This PR addresses an issue where the `fn_transform_cmd` wasn't being applied to the regex query when parsing.
Now, before parsing the regex query, the `fn_transform_cmd` is checked and applied if it exists.
This allows the query to be retrieved and transformed based on user configuration.
Please review and let me know if anything needs adjustment. Thank you!
Fixes #1927

fix(previewer): Apply fn_transform_cmd to regex query parsing

---

lua/fzf-lua/providers/ui_select.lua

The fix for issue #786 breaks setups where user wants a consistent prompt text for all vim.ui.select operations. Previously, this used to be provided in `opts` like below (for eg.):
```lua
require("fzf-lua").register_ui_select(function(ui_opts, _)
return {
prompt = "❯ ",
winopts = {
title = ui_opts.prompt:gsub(":%s*$", ""),
title_pos = "center",
height = 0.33,
width = 0.5
}
}
```
With the updated changes, the prompt provided above is not considered and one must change the provided `ui_opts.prompt` instead.
The changes proposed here prioritize `opts.prompt` if available. Fixes #1952

fix: prioritize opts.prompt if available

---

lua/fzf-lua/previewer/builtin.lua

```
Error executing vim.schedule lua callback: **/fzf-lua/lua/fzf-lua/previewer/builtin.lua:99: Invalid window id: 1016
stack traceback:
[C]: in function 'nvim_win_call'
**/fzf-lua/lua/fzf-lua/previewer/builtin.lua:99: in function 'open'
**/fzf-lua/lua/fzf-lua/previewer/builtin.lua:108: in function 'update'
**/fzf-lua/lua/fzf-lua/previewer/builtin.lua:900: in function 'fn'
**/neovim/runtime/lua/vim/_editor.lua:617: in function 'fn'
**/neovim/runtime/lua/vim/_editor.lua:366: in function <**/neovim/runtime/lua/vim/_editor.lua:365>
```

fix: ts-context nvim_win_call on invalid win

---

lua/fzf-lua/core.lua
tests/win_spec.lua

* Regression of
https://github.com/ibhagwan/fzf-lua/commit/6e61cef02ed41059b4ae3baac791554e1b26f13a:
`not tonumber(idx)` imply list is empty, but select may not empty.
* Don't patch `"" -> nil` when user have it own `v.field_index` which is
unpredictable.
* If user set `field_index = "{q} {n} xxx"`, we shouldn't remove it.

fix(hide): selection is empty when do action on "multi-selected && zero-matched"

---

.github/workflows/vimdoc.yaml
README.md
lua/fzf-lua/devicons.lua
lua/fzf-lua/fzf.lua
lua/fzf-lua/init.lua
lua/fzf-lua/libuv.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/profiles/default.lua
lua/fzf-lua/providers/lsp.lua
lua/fzf-lua/shell.lua
lua/fzf-lua/shell_helper.lua
lua/fzf-lua/spawn.lua
lua/fzf-lua/test/helpers.lua
lua/fzf-lua/utils.lua
lua/fzf-lua/win.lua
plugin/fzf-lua.lua
scripts/headless_fd.sh
tests/win_spec.lua

1. `nvim -l` still quit immediately even with `coroutine.yield`...
```
local co = coroutine.create(function()
coroutine.yield()
os.exit(0)
end)
vim.defer_fn(function()
print('defer done')
coroutine.resume(co)
end, 1000)
coroutine.resume(co)
```
2. `vim.wait` don't work on windows?

fix(rpc): use `nvim -l` to get argv easilier (also less side effects)

---

lua/fzf-lua/_health.lua

Before
```
fzf-lua [optional:media] ~
- ✅ OK 'viu' `viu 1.5.1`
- ✅ OK 'chafa' `Chafa version 1.14.5`
- ✅ OK 'ueberzugpp' `ueberzugpp: error while loading shared libraries: libopencv_videoio.so.410: cannot open shared object file: No such file or directory`
```
After
```
fzf-lua [optional:media] ~
- ✅ OK 'viu' `viu 1.5.1`
- ✅ OK 'chafa' `Chafa version 1.14.5`
- ❌ ERROR 'ueberzugpp' `ueberzugpp: error while loading shared libraries: libopencv_videoio.so.410: cannot open shared object file: No such file or directory`
```

fix(health): not ok when `cmd --version` fail

---

lua/fzf-lua/fzf.lua
lua/fzf-lua/shell_helper.lua

~I search through skim docuemnt `$SKIM` seems for testing purpose only so we can use it.
Otherwise we need to pass `fzf_lua_server` in cli again...~ Ok, there's no $SKIM, it's $SKIM_xx
Since `SKIM_xx` is allowed we use `SKIM_FZF_LUA_SERVER`...
Fix https://github.com/ibhagwan/fzf-lua/pull/1974.
fzf wrap a proxy bash script with tons of lines of `export xx=xx` (`ps aux | rg fzf-temp | rg '\-\-tmux'`)...https://github.com/junegunn/fzf/blob/aefb9a5bc41f92227e4bffa050caca0270b450ba/src/proxy.go#L63.
But this `--proxy-script` is an undocumented option (at least currently)

fix: `skim --tmux` didn't pass all environemnt variable

---

tests/utils_spec.lua
tests/win_spec.lua

It seems a upstream bug: https://github.com/neovim/neovim/issues/12974.
Since job is not cleaned (as the result of `nvim_list_chans()`: https://github.com/ibhagwan/fzf-lua/actions/runs/14485522236/job/40630260016?pr=1967). So the coroutine here https://github.com/ibhagwan/fzf-lua/blob/ba5ba606f11967e08165aeeb9d7abe04d0835f58/lua/fzf-lua/fzf.lua#L329 is always alive: `job.on_exit` -> `co` -> ... -> `win._self` (by upvalues maybe).
You can use a weak table to point to the win instance, then the weak table entry is cleaned only if the coroutine cleaned, ...and only if the job cleaned.).
Send `<c-c>` to fzf stdin to stop it rather than use signal/jobstop/chanclose/bwipeout! (all of them cannot stop/clean the job...).
I cannot reproduce this when interactively use fzf-lua in win10 qemu so just …

fix(test): `setmetatable__gc` on windows

---

lua/fzf-lua/defaults.lua

Fix https://github.com/ibhagwan/fzf-lua/discussions/1928.
Side note:
So the way to implement a `frecency` fzf-lua plugin is `cmd | frecency-sort | fzf --no-sort`
Edit:
That's not very good though... since fzf have to wait frecency-sort finish all sort job... 
thing would be much more easier as long as fzf can give a sort rank on something like prefix score number. then also we can just use spawn.lua to prepend a score retrieval from whatever db while processing the stream.

fix(zoxide): sort by score

---

README.md
doc/fzf-lua.txt

Adds missing `return` statement in docs for the `title_fnamemodify` example.
While testing I kept getting and error regarding a `nil` value so I noticed the `return` statement was missing.
Error without the `return` statement:

docs: fix title_fnamemodify example

---

lua/fzf-lua/previewer/builtin.lua

This is the root cause of https://github.com/ibhagwan/fzf-lua/pull/1913#issuecomment-2810013998.

perf(previewer): don't update if entry is the same as `last_entry`

---

lua/fzf-lua/init.lua
lua/fzf-lua/test/helpers.lua
tests/win_spec.lua

`FzfLua files` -> `<esc>` -> `new` -> `quit` -> `unhide` fail

fix: `:quit` on other window should not kill fzf job

---

lua/fzf-lua/config.lua
lua/fzf-lua/previewer/fzf.lua

https://github.com/ibhagwan/fzf-lua/issues/1834#issuecomment-2878875713
I delete `result` event since it seems unused?

fix(previewer): opts.line_query in fzf previewer

---

README.md
lua/fzf-lua/defaults.lua
lua/fzf-lua/previewer/builtin.lua

- Adds `render_inline` prop to control whether to do image inline render in fzf-lua builtin previewer or not.
- This options is added because as explained in https://github.com/ibhagwan/fzf-lua/issues/2064 if inline render is enabled in Snacks, fzf-lua is detecting this option and applying it to the previewer as well.
- Enables the user to control better customization having a separate option for the previewer.

feat(image): add option to control image inline render

---

README.md
doc/fzf-lua.txt
lua/fzf-lua/defaults.lua
lua/fzf-lua/providers/diagnostic.lua

This implements the changes discussed in https://github.com/ibhagwan/fzf-lua/issues/2067:
- Highlight the file headers with the diagnostic color (warnings = orange etc.)
- Append the diagnostic code to the message if present
Both are disabled by default and can be enabled with the `color_headings` and `diag_code` options.

feat(diagnostics): add options to color headings and show diag code

---

lua/fzf-lua/defaults.lua
lua/fzf-lua/providers/nvim.lua

```lua
-- Save one more type
require('fzf-lua').commands({ flatten = { Gitsigns = true } })
-- Discovery (all commands)
require('fzf-lua').commands({ flatten = vim.api.nvim_get_commands {} })
-- Customization
require('fzf-lua').commands({ flatten = { Foo = function(opts) return { 'Bar', 'Baz --abc' } end } })
```

feat(commands): include subcommands

---

lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/providers/dap.lua
lua/fzf-lua/types.lua

Some debuggers are _asynchronous_. It means that the debugging and the code execution doesn't happen at the same time. An example of this is [coredumpy](https://github.com/gaogaotiantian/coredumpy). In their implementation, the source code that triggered the error is saved in a dump file, which can be loaded later. This can even be loaded on a different machine/system. In this case, the files on the local filesystem are often ignored because they're not guaranteed to be the same as the source code which caused the error (or simply don't exist at all).
This PR attempts to load the source code saved in the dump file (provided by the dap server). This enables frame previewing when working with a dump file from [coredumpy](https://github.com/gaogaotiantian/coredumpy) using …

Load content from dap server

---

lua/fzf-lua/defaults.lua

This change wraps the function `_man_cmd_fn` which checks the system to find which man previewer is installed. This system check is expensive and does not need to be called until it is actually required. This reduces the startup time of fzf-lua. An example of the difference via [vim-startuptime](https://github.com/dstein64/vim-startuptime):
```
event                  time percent
fzf-lua               41.34   42.38
fzf-lua.config        37.96   38.91
fzf-lua.defaults      37.57   38.51
```
```
event                  time percent
fzf-lua                3.29    5.66
fzf-lua.config         0.98    1.69
fzf-lua.path           0.67    1.15
fzf-lua.defaults       0.53    0.91
```
Relates: #970

perf: improve startup time by deferring config defaults

---

lua/fzf-lua/actions.lua

Anyway I want to avoid show twice when enable `vim._extui`

fix(actions): `:hi` executed twice

---

lua/fzf-lua/providers/lsp.lua

With 1 result, the cursor will jump to the location but the fzf window also opens
Avoid opening the window by relying on the jump1 logic inside gen_lsp_contents()

fix(call_hierarchy): Don't open fzf window with 1 result and `opts.jump1`

---

lua/fzf-lua/win.lua

Allow focusing the preview window, since there's already a keymap to focus the fzf input from the preview window.

feat: allow keymap to focus preview window

---

lua/fzf-lua/defaults.lua

By default `fd` only respects global or local gitignore rules if searching inside a git repository. However in certain scenarios, e.g. when using [jujutsu](https://github.com/jj-vcs/jj) instead of git, this approach never takes effect since it can't find a .git directory in cwd.
The proposed `--no-require-git` flag allows `fd` to respect all git related ignore rules, regardless of whether it's searching inside a git repo or not.
I think it's safe to include this flag in default cmd.

fix(picker): file picker not respecting .gitignore

---

lua/fzf-lua/utils.lua

Fixing https://github.com/ibhagwan/fzf-lua/issues/2196 bug introduced in https://github.com/ibhagwan/fzf-lua/commit/a9803618d77bd024d97de75cf5878819d4d6a2d0#diff-6610b6cdb84f62055c6687508d2346e099b304fe0095ff33b8fed55474cd77aaR848

fix: `utils.setup_highlights` to not always override colorscheme hl groups

---

lua/fzf-lua/defaults.lua
lua/fzf-lua/previewer/builtin.lua

fix #2209. I couldn't reproduce #500 as ` vim.api.nvim_win_set_cursor(preview_winid, self.orig_pos)` is no longer run when scrolling, but only when `direction` is `"reset"`. also why not just use `Hgk` and `Lgj` for `line-up` and `line-down`? it works fine for what I tested.

fix: #2209 and improve builtin previewer scrolling

---

lua/fzf-lua/types.lua

I just noticed that I had some LSP warnings about required missing fields in my configuration.
There might be other types that have optional fields, but I'm just modifying the ones I'm confident about for now.

chore(lua_ls): make some fields optional

---

lua/fzf-lua/config.lua
lua/fzf-lua/types.lua

- **refactor(config): extract normalize_tbl to expand dot keys**
- **fix(config): `FzfLua blines profile=ivy winopts.treesitter.enabled=false`**
Not sure if this a correct fix but it work for me.

fix: FzfLua blines profile=ivy winopts.treesitter.enabled=false

---

lua/fzf-lua/actions.lua
lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/providers/nvim.lua
lua/fzf-lua/types.lua
lua/fzf-lua/utils.lua
lua/fzf-lua/win.lua
tests/utils_spec.lua

- **refactor: always setlocal on window options**
* chore: remove useless autocmd
* refactor: move logic to win:resized, win:save_size
* refactor: simplify utils.eventignore
- **fix(previewer): prefer winopts.winhl (useful with non-float window as previewer)**

refactor: always setlocal on window options

---

lua/fzf-lua/providers/lsp.lua

for `Global` picker:
i want to write like:
```lua
pickers = {
{ "frecency", desc = "Files" },
{ "buffers", desc = "Bufs", prefix = "$" },
{ "lsp_document_symbols", desc = "Symbols (buf)", prefix = "@", { silent = true } },
{ "lsp_workspace_symbols", desc = "Symbols (project)", prefix = "#", { silent = true } },
},
```
but `silent` peremeter seems useless when i passing, so i passed here.
i don't know if this "not pass `opts.silent`" is designed.

fix(config): pass `silent` to lsp provider

---

lua/fzf-lua/previewer/builtin.lua
lua/fzf-lua/types.lua

Example: `/path/to/xx.txt` with modeline in it saying it's `cmake`.

fix(previewer): re-detect filetype on poor filetype

---

lua/fzf-lua/actions.lua

Hi @ibhagwan,
I encountered an edge case where if vim.api.nvim_win_set_buf results in autocmd that eventually decides to open the buffer elsewhere, the current window is switched back to the place where it was, I don't know if that's a neovim bug or something that is by design, here is my attempt to fix this by checking whether the current window contains the buffer, and if not - switch to the window where the buffer is.
The use case for such autocmd to decide to open the buffer elsewhere is for example if the buffer is about to open in like a file explorer or something. The winfixbuf doesnt resolve this nicely, this is what I am doing:
https://github.com/eyalz800/nvim.lua/blob/main/lua/plugins/pin.lua
What happens is that nvim_win_set_buf triggers my open_in_best_win function which opens …

fix(actions): switch to correct buffer window on special set buf autocmd

---

lua/fzf-lua/providers/nvim.lua

Commit 4cb7d7c614a55d55dcc175c2457b7be0cbbdecec didn't fully address the github issue
Addresses #2353
It looks like this now:

feat: Replace local buf global mark output with highlighted text

---

lua/fzf-lua/providers/nvim.lua

Fail to call `:FzfLua commands` with buffer-local commands.

fix(commands): cmd_global -> [opts.hls.cmd_global]

---

lua/fzf-lua/utils.lua

This [commit](https://github.com/ibhagwan/fzf-lua/commit/464bab1fe59c4b92f3a19eda86b1d8536f40d8ad#diff-6610b6cdb84f62055c6687508d2346e099b304fe0095ff33b8fed55474cd77aaR1473) introduced a regression in nvim 0.11+. If a treesitter parser isn't installed, it shows a warning. The functionality before this commit, was to swallow the warning and highlight the buffer with whatever colors it could, if any at all.
This PR aims to restore the original functionality, without affecting older neovim versions.
An example of a warning is shown below:

fix(preview): swallow warning for missing ts parsers

---

lua/fzf-lua/actions.lua
lua/fzf-lua/config.lua

I've been using this patch for a while, and as suggested [here](https://github.com/ibhagwan/fzf-lua/discussions/1268) created a new action, so the default behaviour is not changed

Add action that avoids splitting when opening help
