ibhagwan/fzf-lua

- README.md
Sorry, I should have included this in the last PR.
> Update README to reference new default git actions

- lua/fzf-lua/libuv.lua
Instead of opening a new file descriptor on /dev/stdout and /dev/stderr, simply use builtin io module.
MacOS in particular doesn't seem to like processes opening /dev/stdout and /dev/stderr. Or at the very least there are some hidden nuances there that aren't actually necessary since Lua's builtin io module can already take care of writing to the pre-opened stdout and stderr file descriptors.
Fixes #251 and possibly #248
> Fix multiprocess mode pipes to use io.write() 

- lua/fzf-lua/providers/lsp.lua
In Neovim `v0.8` the `resolved_capabilities` is deprecated and is replaced by the `server_capabilities`. The `capability` property of the handlers table is split into `resolved_capability` and `server_capability`, and in the `wrap_module_fncs` is set back based on the neovim's version.
Please let me know if this is not the right way to approach this problem.
> ref(lsp): add server_capabilities support on 0.8

- README.md
Hello, just a minor omission I noticed when syncing up my configuration settings.  As always thanks for the work!
> README: add missing ','s

- README.md
- lua/fzf-lua/config.lua
- lua/fzf-lua/previewer/builtin.lua
- lua/fzf-lua/win.lua
change alignment of the preview title
default is left
> previewer: Add title_align option

- lua/fzf-lua/win.lua
add a buffer local autocmd which will trigger the redraw() function
> feat(win): Automatically resize windows if screen change is detected

- scripts/fzf-lua-scm-1.rockspec
to allow an install via luarocks
> add rockspec

- lua/fzf-lua/actions.lua
- lua/fzf-lua/cmd.lua
- lua/fzf-lua/config.lua
- lua/fzf-lua/core.lua
- lua/fzf-lua/fzf.lua
- lua/fzf-lua/init.lua
- lua/fzf-lua/libuv.lua
- lua/fzf-lua/make_entry.lua
- lua/fzf-lua/path.lua
- lua/fzf-lua/previewer/builtin.lua
- lua/fzf-lua/previewer/fzf.lua
- lua/fzf-lua/providers/buffers.lua
- lua/fzf-lua/providers/diagnostic.lua
- lua/fzf-lua/providers/git.lua
- lua/fzf-lua/providers/grep.lua
- lua/fzf-lua/providers/lsp.lua
- lua/fzf-lua/providers/module.lua
- lua/fzf-lua/providers/tags.lua
- lua/fzf-lua/providers/ui_select.lua
- lua/fzf-lua/shell.lua
- lua/fzf-lua/utils.lua
- lua/fzf-lua/win.lua
> fix(init.lua): fix typo in comment

- lua/fzf-lua/actions.lua
- lua/fzf-lua/config.lua
- lua/fzf-lua/defaults.lua
Hello, trying to contribute here. Hope it makes sense.
Though I notice you use the `│` instead of `|` as the divider. It took me a few minutes to figure it out :D
> Apply keymap when select.

- README.md
> Update grep rg_opts in README.md to match actual value

- lua/fzf-lua/providers/nvim.lua
See #883. Separated from #883.
> fix(actions): Do not override header if it's already given in opts

- lua/fzf-lua/win.lua
Should fix #1022 
So far I only tested it briefly, but it should fix the issue by removing all windows from the restore command that do not exists anymore. Happy for feedback or help with testing.
> fix: only restore split layout for existing windows

- lua/fzf-lua/win.lua
Should actually fix #1022 
I don't know how my former PR #1024 even worked, but I thought it did :sweat_smile: 
I was to fast pushing a "solution". This here should resolve the actual issue. Sorry for the "spam"
> fix: window layout restorage

- lua/fzf-lua/profiles/fzf-native.lua
- lua/fzf-lua/profiles/fzf-tmux.lua
- lua/fzf-lua/profiles/max-perf.lua
The codeaction issue made me remember that I wanted to PR this
> Set proper native codeaction previewer for native profiles

- lua/fzf-lua/profiles/fzf-native.lua
- lua/fzf-lua/profiles/fzf-tmux.lua
- lua/fzf-lua/profiles/max-perf.lua
Not sure why I missed it but it should be code_actions not codeactions.
> Add missing _ to profile codeactions profile previewer

- .github/workflows/luarocks-release.yaml
> ci: bump luarocks-tag-release to v5

- lua/fzf-lua/providers/ui_select.lua
> fix(ui_select): check if an item has been selected

- lua/fzf-lua/win.lua
> feat: add nowait to `<esc>` keymap

- lua/fzf-lua/_health.lua
> fix(health): check for `batcat`

- lua/fzf-lua/actions.lua
https://github.com/ibhagwan/fzf-lua/pull/1409 had a small typo and I caught it first haha
```
Error executing vim.schedule lua callback: Vim:E117: Unknown function: confim
```
> fix(actions): fix git_reset

- lua/fzf-lua/previewer/builtin.lua
Fix https://github.com/ibhagwan/fzf-lua/pull/1419#issuecomment-2328157264
> fix(jumps): when no match items

- lua/fzf-lua/make_entry.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/1443.
> fix: escape "%" in gsub target

- lua/fzf-lua/profiles/telescope.lua
Telescope jump to the result if number of result is 1. Add option for lsp for telescope profile to match this behavior
> Jump to single result in lsp for telescope profile

- lua/fzf-lua/providers/lsp.lua
> feat(lsp): Support `jump_to_location` for incoming/outgoing calls

- lua/fzf-lua/previewer/builtin.lua
To enable
```lua
require("fzf-lua").setup({
previewer = { builtin = { treesitter = { context = true} } }
})
```
> feat(previewer): display `nvim-treesitter-context` (#1552)

- lua/fzf-lua/providers/nvim.lua
Remove the unintentional print statement.
> remove unintentional print statement in registers filters

- lua/fzf-lua/libuv.lua
- lua/fzf-lua/shell.lua
Related https://github.com/neovim/neovim/pull/32137.
> fix: set TMPDIR for child to avoid lots of logging

- .github/workflows/tests.yaml
- tests/devicons_spec.lua
- tests/minicons_spec.lua
> ci: added macos, windows

- lua/fzf-lua/actions.lua
- lua/fzf-lua/defaults.lua
- lua/fzf-lua/providers/nvim.lua
Close https://github.com/ibhagwan/fzf-lua/issues/1792.
> feat: add `mark_del` action

- lua/fzf-lua/fzf.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/1789.
> fix: use async callback avoid block when open fifo

- OPTIONS.md
- doc/fzf-lua-opts.txt
Embedded GitHub editor adds '\n' to the last line.
I can fix fit's a critical change, I didn't fork it locally in order to make the PR
> Add live_grep search_paths option to doc

- lua/fzf-lua/core.lua
- lua/fzf-lua/providers/nvim.lua
2ab648faf fixed custom headers but broke default headers for
command|search history.
> fix(history): Restore the default header

- lua/fzf-lua/providers/files.lua
- tests/file/ui_spec.lua
Per our discussion here: https://github.com/ibhagwan/fzf-lua/issues/1795
> Fix alt-h/alt-i issue with `opts.cmd`

- lua/fzf-lua/config.lua
Fix https://github.com/ibhagwan/fzf-lua/discussions/1870#discussioncomment-12535353.
```lua
require('fzf-lua').setup {
tabs = {
keymap = function()
local curtab = fn.tabpagenr()
local pos = 1
for i, t in ipairs(api.nvim_list_tabpages()) do
if i < curtab then pos = pos + 1 + #api.nvim_tabpage_list_wins(t) end
end
return { fzf = { load = string.format("transform:echo 'pos(%d)'", pos) } }
end,
},
}
```
> feat: more table options can be function

- lua/fzf-lua/providers/buffers.lua
- lua/fzf-lua/providers/colorschemes.lua
- lua/fzf-lua/providers/dap.lua
- lua/fzf-lua/providers/files.lua
- lua/fzf-lua/providers/git.lua
- lua/fzf-lua/providers/nvim.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/1904.
> fix: don't use unused `{+}` to avoid `{+}` is not expand when there's no match

- lua/fzf-lua/shell.lua
Silent all error message make it hard to debug things...
> fix: don't ignore err in action

- lua/fzf-lua/previewer/builtin.lua
`:FzfLua files query=screenshots`, then scroll.
> fix(previewer): scroll previewer on buffer without ft detected

- lua/fzf-lua/actions.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/1949.
> fix(actions): argdel only accept relative path

- lua/fzf-lua/win.lua
Fix https://github.com/ibhagwan/fzf-lua/discussions/1979.
> fix: pass winopts.hide to `nvim_open_win`

- lua/fzf-lua/actions.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/1989.
> fix(actions): spell_apply on insertmode

- lua/fzf-lua/defaults.lua
- lua/fzf-lua/providers/nvim.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/1989#issuecomment-2814514886.
> fix(actions): reuse actions.complete for spell

- lua/fzf-lua/actions.lua
- lua/fzf-lua/config.lua
- lua/fzf-lua/providers/nvim.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/1989#issuecomment-2814514886 again.
> fix(actions): resume insertmode when complete abort

- lua/fzf-lua/win.lua
`FzfLua files` -> `hide` -> resize terminal -> `unhide` -> broken layout
> fix: VimResized when fzf buffer hidden

- README.md
- lua/fzf-lua/defaults.lua
- lua/fzf-lua/previewer/builtin.lua
- lua/fzf-lua/utils.lua
- lua/fzf-lua/win.lua
- tests/win_spec.lua
To make local image preview need something upstream: https://github.com/folke/snacks.nvim/pull/1618.
But I think it have been work for url image/latex.
And note your must set `winblend=0` for kitty backend, https://github.com/folke/snacks.nvim/pull/1615.
> feat: support snacks.image

- lua/fzf-lua/previewer/builtin.lua
When use `lazy.nvim`, it will auto generate markdown tags for those plugin have no vimdoc.
e.g. `nvim-bqf`
```vim
:FzfLua helptags query=nvim-bqf winopts.preview.hidden=false
```
> fix(preview): `helptags()` cannot preview markdown help buffer

- lua/fzf-lua/actions.lua
* when clipboard=unnamed,unnamedplus
* Also some nil check when no selected.
> fix(actions): when clipboard=unnamed,unnamedplus

- lua/fzf-lua/_health.lua
Added `mini.icons` check along with `nvim-web-devicons`
> updated health check

- lua/fzf-lua/previewer/builtin.lua
See https://github.com/nvim-treesitter/nvim-treesitter-context/pull/591.
> fix: don't override global zindex for ts-context win

- lua/fzf-lua/test/helpers.lua
- lua/fzf-lua/test/screenshot.lua
- scripts/make_cli.lua
- tests/win_spec.lua
- **ci: can assert screenshot in lua file**
- **ci: fix test**
- **ci: add case filter**
> ci inline screenshot

- README.md
- lua/fzf-lua/defaults.lua
- lua/fzf-lua/init.lua
- lua/fzf-lua/providers/git.lua
I've added a new command: `git_diff` that works with a branch name.
I needed this for my work, because I don't remember what files I've changed in the past on a single branch.
So basically, this is only for me!
If you want to merge it, I'm open to suggestions.
_(I don't have enough experience with this code base, and just edited the `git_status` command to make it work.)_
> feat: show diff with any branch

- lua/fzf-lua/previewer/builtin.lua
- lua/fzf-lua/utils.lua
- lua/fzf-lua/win.lua
- **Revert "fix(tx-context): revert 1cc70fb29e63ff26acba1e0cbca04705f8a485f1."**
- **debug.getupvalues**
> debug.getupvalue hacks on ts context win

- lua/fzf-lua/previewer/builtin.lua
https://github.com/nvim-treesitter/nvim-treesitter-context/commit/33b3f5a06ded3f3dcbf5de433d1ea35caa9b14d3
> fix(ts-context): upstream changes

- lua/fzf-lua/previewer/builtin.lua
Fix https://github.com/ibhagwan/fzf-lua/pull/2079#issuecomment-2912855760.
> fix(ts-context): update zindex when toggle context win

- lua/fzf-lua/providers/buffers.lua
https://github.com/ibhagwan/fzf-lua/issues/2103
Copy paste from `locals.lua`. Not sure if this will work with `master` branch.
> fix(treesitter): use locals.scm only

- lua/fzf-lua/win.lua
https://github.com/ibhagwan/fzf-lua/discussions/2121#discussioncomment-13540614
> fix(win): consider border width

- lua/fzf-lua/config.lua
Fix https://github.com/ibhagwan/fzf-lua/issues/2149.
> fix(config): always remove the first boolean

- lua/fzf-lua/complete.lua
- lua/fzf-lua/core.lua
- lua/fzf-lua/fzf.lua
- lua/fzf-lua/libuv.lua
- lua/fzf-lua/make_entry.lua
- lua/fzf-lua/providers/files.lua
- lua/fzf-lua/providers/git.lua
- lua/fzf-lua/providers/grep.lua
- lua/fzf-lua/providers/lsp.lua
- lua/fzf-lua/shell.lua
- **refactor: move mt_cmd_wrapper into stringify**
> fix move into stringify

- lua/fzf-lua/profiles/telescope.lua
This is the default behavior in Telescope
> add cycle to fzf_opts in telescope profile

- lua/fzf-lua/win.lua
cleanups from this pr: https://github.com/ibhagwan/fzf-lua/pull/2168
> fix: formatting + remove logging statment

- lua/fzf-lua/core.lua
- lua/fzf-lua/shell.lua
- tests/files_spec.lua
Regression from f0e830e278ad954a4e545928f8bfe08725a71173
fix: opts.__pid -> opts.PidObject
> fix(hide): actions should be nop when nothing match

- tests/win_spec.lua
@phanen, any objections for this fix?
> ci: fix flakey keymap test

- lua/fzf-lua/actions.lua
- tests/actions_spec.lua
fix https://github.com/ibhagwan/fzf-lua/issues/2295
> fix: vim.cmd.drop in actions

- lua/fzf-lua/path.lua
- lua/fzf-lua/previewer/builtin.lua
- lua/fzf-lua/previewer/fzf.lua
- lua/fzf-lua/types.lua
> fix: show debug information

- lua/fzf-lua/shell.lua
- tests/api_spec.lua
> fix(global): disable multiprocess for function contents

- lua/fzf-lua/data/colorschemes.json
- lua/fzf-lua/previewer/builtin.lua
- lua/fzf-lua/providers/buffers.lua
- lua/fzf-lua/utils.lua
- lua/fzf-lua/win.lua
> fix: memoize has_ts_parser call
